### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#3]
When it's up, the site needs a design review: 
- Since it's just a subset of the caleydo site, I've removed the banner buttons... but it looks pretty bare now.
- Old Caleydo logo has vectorized text. Replaced it with <text>... but the Helvetica is too skinny in that role.
- I got rid of the title, since everything was "Documentation", but maybe it should come back and be used more appropriately?
- Does the sidebar idiom work? At the very least, I think we should highlight the current page for context... but even then, if this list gets longer than the window height it's not going to work well.

**Comment by ngehlenborg** [comment]
Regarding the sidebar menu: It will definitely break as we add more content to the documentation. 

We should try to break up documentation (over generally our Phovea site content) across top-level navigation items (e.g. one for API docs, one for tutorials, one for project overview/description, etc.) and use the existing navigation structure (currently removed) that exists in the Caleydo site.

Since we will still need within-section navigation, we should look into integrating something like the Bootstrap menu: http://getbootstrap.com/components/ (click around to see how it deals with second-level entries, e.g. http://getbootstrap.com/components/#btn-groups).

**Comment by mstreit** [comment]
...and we should use the Phovea logo instead of the Caleydo logo.

**Comment by ngehlenborg** [comment]
@ngehlenborg will work on the logo.

**Comment by mccalluc** [comment]
I think this is almost done.
- Caleydo hexagon still in the favicon... but maybe that's best?
- Caleydo hexagon in footer... Get rid of that, and don't replace it? We have the logo in the upper left.
- Get rid of the social media links? They are all about caleydo really, and aren't too active in any event.

I'll add another commit with the deletions.

**Comment by mccalluc** [comment]
Closing: I think it looks good. If there are small issues that remain, please open new tickets.
